# Generated by Django 5.2.7 on 2025-11-06 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='swap',
        ),
        migrations.AddField(
            model_name='agent',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_swap_amount',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=14),
        ),
        migrations.AddField(
            model_name='agent',
            name='response_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='location_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('from_service', models.CharField(choices=[('bank', 'Bank Account'), ('mpamba', 'TNM Mpamba'), ('airtel_money', 'Airtel Money')], max_length=15)),
                ('to_service', models.CharField(choices=[('TNM', 'TNM Mpamba'), ('AIRTEL', 'Airtel Money')], max_length=10)),
                ('dest_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Agent Acceptance'), ('ACCEPTED', 'Accepted by Agent'), ('REJECTED', 'Rejected by Agent'), ('RESERVED', 'Reserved'), ('PAID_BANK', 'Paid to Agent Bank'), ('SENT_WALLET', 'Agent Sent Wallet'), ('COMPLETE', 'Complete'), ('DISPUTE', 'Dispute'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agent_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_deposit_proof', models.FileField(blank=True, upload_to='proofs/bank/')),
                ('agent_tx_id', models.CharField(blank=True, max_length=128)),
                ('agent_response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='swap_app.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('swap_request', 'Swap Request'), ('swap_accepted', 'Swap Accepted'), ('swap_rejected', 'Swap Rejected'), ('payment_received', 'Payment Received'), ('payment_sent', 'Payment Sent'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('swap_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swap_app.swaprequest')),
            ],
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='swap_request',
            field=models.ForeignKey(default=6112025, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='swap_app.swaprequest'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Swap',
        ),
    ]
